spring:
  application:
    name: server-service

server:
  port: 9099

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  routes:
    client-service:
      path: /client-service/**
      url: http://localhost:8031